name: demo
on: [push]
jobs:
  get-feature-branch:
    outputs:
      BRANCH_NAME: EI-123
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo $BRANCH_NAME

  delete-branch:
    runs-on: ubuntu-latest
    needs: get-feature-branch
    steps:
      - name: echo
        run: echo "BRANCH_ID = ${{ needs.get-feature-branch.outputs.BRANCH_NAME }}"
      - name: lowercase
        shell: bash
        run: echo "${{ needs.get-feature-branch.outputs.BRANCH_NAME }}" | sed -e 's/\(.*\)/\L\1/' | sed 's/-//g'
